# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8ba6491d2652116ec6246df3155f6744fc66cd39bdfc941cd3b8f3234a54c2ebb5a0bb91b863edf94034affc6a6419fdef247d19a0d65e868d815a34d9f59da

test:
  secret_key_base: 7e598072084737666ecebf82a37b3801c134ef67a526f4cd9fc8be31e54a0775b06ed13391a6a062eab745cfe18c4b86e1640305d9bb1a706c3703ee15ed85ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
